# Generated by Django 5.2.5 on 2025-08-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_store_custo_last_na_e6a359_idx_store_custo_last_na_2e448d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
